config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'pages', to: 'pages#contact'

  resources :portofolios

  get 'portofolio/:id', to: 'portofolios#show', as: 'portofolio_show'
  get 'angular-items', to: 'portofolios#angular'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "https://place-hold.it/#{height}X#{width}"
  end
end

app/models/portofolio.rb
#frozen_string_literal: true
class Portofolio < ApplicationRecord
  include Placeholder

  # validations
  validates_presence_of :title, :body, :main_image, :thumb_image

  # relationships
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs ['name'].blank? }

  # scopes
  scope :ruby_on_rails_portofolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image  ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
  end

  def self.angular
    where(subtitle: 'Angular')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: 250, width: 250)
  end
end

app/models/technology.rb
# frozen_string_literal: true

class Technology < ApplicationRecord
  belongs_to :portofolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    name.split.first
  end

  def last_name
    name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
  include TrackSource
  include CurrentUserConcern
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]

  def index
    @blogs = Blog.all
  end

  def show; end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.draft!
    end

    redirect_to blogs_url, notice: 'Post Status Was Updated'
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user 
  end

  def guest_user 
    OpenStruct.new(name: "Guest User",
                   first_name: "Guest",
                   last_name: "User",
                   email: "sample@sample.com")
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/track_source.rb
module TrackSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] == params[:q] if params[:q]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about; end

  def contact; end
end

app/controllers/portofolios_controller.rb
class PortofoliosController < ApplicationController
  before_action :set_portfolio, only: %i[show edit update destroy]

  def index
    @portofolio_items = Portofolio.all
  end

  def angular
    @angular_portofolio_items = Portofolio.angular
  end

  def new
    @portofolio_item = Portofolio.new
    3.times { @portofolio_item.technologies.build }
  end

  def create
    @portofolio_item = Portofolio.new(portofolio_params)

    respond_to do |format|
      if @portofolio_item.save
        format.html { redirect_to portofolios_path, notice: 'Portofolio was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def edit; end

  def update
    respond_to do |format|
      if @portofolio_item.update(portofolio_params)
        format.html { redirect_to portofolios_path, notice: 'Portofolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portofolio_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portofolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portofolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portofolios_path, notice: 'Portofolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_portfolio
    @portofolio_item = Portofolio.find(params[:id])
  end

  def portofolio_params
    params.require(:portofolio).permit(:title,
                                       :subtitle,
                                       :body,
                                       technologies_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portofolios_helper.rb
module PortofoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortofolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user.is_a?(User) %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    
    <%= yield %>

    <% if session[:source].present? %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name %></h1>

<p>Find me in app/views/pages/home.html.erb</p>

<h1> Blog Posts </h1>
<%= @posts.inspect %>

<h1> SKills </h1>
<%= @skills.inspect %>

app/views/portofolios/angular.html.erb
<h1> Angular Portofolio Index </h1>

<%= link_to "Create New Portofolio", new_portofolio_path %>

<% @angular_portofolio_items.each do |portofolio_item| %>

  <p> <%= link_to portofolio_item.title, portofolio_show_path(portofolio_item) %></p>
  <p> <%= portofolio_item.subtitle %></p>
  <p> <%= portofolio_item.body %></p>
  <p> <%= image_tag portofolio_item.thumb_image if portofolio_item.thumb_image.present? %></p>

  <p> <%= link_to "Edit", edit_portofolio_path(portofolio_item) %></p>
  <p> <%= link_to "Delete", portofolio_item, method: :delete, data: { confirm: 'U sure deleting it, you punk ?' }%> </p>
<% end %>

app/views/portofolios/edit.html.erb
<h1> Edit a new Portofolio Item </h1>

<%= form_for(@portofolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portofolios/index.html.erb
<h1> Portofolio Index </h1>

<%= link_to "Create New Portofolio", new_portofolio_path %>

<% @portofolio_items.each do |portofolio_item| %>

  <p> <%= link_to portofolio_item.title, portofolio_show_path(portofolio_item) %></p>
  <p> <%= portofolio_item.subtitle %></p>
  <p> <%= portofolio_item.body %></p>
  <p> <%= image_tag portofolio_item.thumb_image if portofolio_item.thumb_image.present? %></p>

  <p> <%= link_to "Edit", edit_portofolio_path(portofolio_item) %></p>
  <p> <%= link_to "Delete", portofolio_item, method: :delete, data: { confirm: 'U sure deleting it, you punk ?' }%> </p>
<% end %>

app/views/portofolios/new.html.erb
<h1> Create a new Portofolio Item </h1>

<%= form_for(@portofolio_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portofolios/show.html.erb
<%= image_tag @portofolio_item.main_image if @portofolio_item.main_image.present? %>

<h1> <%= @portofolio_item.title %>    </h1>

<em> <%= @portofolio_item.subtitle %> </em>

<p> <%= @portofolio_item.body %>  </p>

<h2> Technologies Used: </h2>

<% @portofolio_item.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>

<hr>